name: station_meteo
description: A weather station application that uses MQTT to monitor temperature, humidity, and wind speed.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  mqtt_client: ^9.8.1
  fl_chart: ^0.66.0
  lottie: ^2.3.2
  intl: ^0.18.0
  connectivity_plus: ^3.0.3
  shared_preferences: ^2.2.0
  cupertino_icons: ^1.0.5
  supabase_flutter: ^1.10.25

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true